LANGUAGES = {
    "en": "English",
    "pt": "Português (Brasil)",
    "es": "Español",
    "fr": "Français",
    "it": "Italiano",
    "de": "Deutsch",
    "zh-CN": "中文（简体）",
    "ja": "日本語",
    "ru": "Русский",
    "ar": "العربية",
    "hi": "हिन्दी",
    "ko": "한국어",
    "nl": "Nederlands",
    "sv": "Svenska",
    "da": "Dansk",
    "fi": "Suomi",
    "no": "Norsk",
    "pl": "Polski",
    "tr": "Türkçe",
    "el": "Ελληνικά",
    "he": "עברית",
    "id": "Bahasa Indonesia",
    "th": "ไทย",
    "cs": "Čeština",
    "hu": "Magyar",
    "ro": "Română",
    "sk": "Slovenčina",
    "uk": "Українська",
    "vi": "Tiếng Việt",
    "bg": "Български"
}
